site_name: Orion Documentation
site_description: Official documentation for Orion - Advanced FAWE Add-on.
site_author: Almarel
site_url: https://almarelplugins.github.io/orion-docs/

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  features:
    - navigation.sections # Делает группы в меню в виде красивых блоков
    - navigation.path     # Добавляет "хлебные крошки" под черной шапкой
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

extra_css:
  - stylesheets/custom.css # Подключаем наш файл дизайна

copyright: Copyright &copy; 2024 Almarel Plugins

# Группируем меню для энтерпрайз-вида
nav:
  - Introduction: index.md
  - Tools:
      - Brushes: brushes.md
      - Masks: masks.md
      - Patterns: patterns.md
  - Reference:
      - Commands: commands.md
      - Permissions: permissions.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg